name: webviewx_example
description: A new Flutter project.

publish_to: "none"

version: 2.2.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter

  webviewx:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/
