name: webviewx_example
description: A new Flutter project.

publish_to: "none"

version: 2.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter

  webviewx:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  uses-material-design: true

  assets:
    - assets/
