name: webviewx
description: A feature-rich cross-platform webview using webview_flutter for
  mobile and iframe for web. JS interop-ready.
homepage: https://github.com/adrianflutur/webviewx
version: 0.3.1

environment:
  sdk: ">=3.2.5 <4.0.0"
  flutter: ">=3.16.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ">=1.2.0 <2.0.0"
  path: ">=1.8.2 <2.0.0"
  pointer_interceptor: ">=0.9.3+4 <1.0.0"
  uuid: ">=4.0.0 <5.0.0"
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
