name: webviewx
description: A feature-rich cross-platform webview using webview_flutter for
  mobile and iframe for web. JS interop-ready.
homepage: https://github.com/adrianflutur/webviewx
version: 0.2.1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  path: ^1.8.2
  pointer_interceptor: ^0.9.3+4
  uuid: ^3.0.4
  webview_flutter: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.6.0
